{{ range .Values.pods }}
apiVersion: v1
kind: Pod
metadata:
  name: webapp-{{ . }}
  labels:
    app: webapp
spec:
  containers:
  - image: "nginx:latest"
    name: webapp-container
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "{{ . }}m"
---
{{ end }}